export type CompletionShell = 'bash' | 'zsh' | 'fish';

export type CliArgs = {
  command?: string;
  subcommand?: string;
  target?: string;
  json: boolean;
  tui: boolean;
  write: boolean;
  save: boolean;
  input?: string;
  session?: string;
  provider?: 'auto' | 'shared-llm' | 'decentralized-llm' | 'local-fallback' | 'ollama';
  model?: string;
  file?: string;
  out?: string;
  confirmWrite: boolean;
  key?: string;
  value?: string;
  passphrase?: string;
  recoveryQuestion?: string;
  recoveryAnswer?: string;
  id?: string;
  query?: string;
  to?: string;
  latest?: number;
  port?: number;
  transport?: 'stdio' | 'http';
  durationMs?: number;
  topK?: number;
  tuned?: boolean;
  strategy?: 'default' | 'latency-aware';
  interactive: boolean;
  nonInteractive: boolean;
  profile?: 'dev-local' | 'prod-shared' | 'prod-decentralized' | 'ollama-local';
  force: boolean;
  fix?: boolean;
  deep?: boolean;
  apply: boolean;
  dryRun: boolean;
  yes: boolean;
  schema: boolean;
  verbose: boolean;
  maxTokens?: number;
  contextWindow?: number;
  temperature?: number;
  systemPrompt?: string;
  taskType?: 'chat' | 'code' | 'analysis' | 'creative';
  priority?: 'latency' | 'cost' | 'quality';
  minContext?: number;
  vision: boolean;
  functions: boolean;
  size?: 'small' | 'medium' | 'large';
  reset: boolean;
  chain?: string;
  cid?: string;
  recipient?: string;
  blocks?: string;
  offerId?: string;
  days?: number;
  repoPath?: string;
  agent?: string;
  list: boolean;
  clean: boolean;
  restore?: string;
  keep?: number;
  tag?: string;
  format?: 'table' | 'json' | 'csv';
  intervalMs?: number;
};
